from setuptools import setup, find_packages

setup(
    name='django-secure-contact-form',
    version='0.3.0',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'Django>=4.0',
        'django-simple-captcha>=0.5.14',
        'Pillow>=8.0.0',
    ],
    python_requires='>=3.8',
    license='MIT',
    description='A secure, customizable Django contact form package with CAPTCHA, honeypot spam protection, and timestamp validation.',
    long_description=open('README.md', encoding='utf-8').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/Gavin-Humphrey/django-secure-contact-form',
    author='Gavin Humphrey',
    author_email='gavin.humphrey.pro@gmail.com',
    classifiers=[
        'Environment :: Web Environment',
        'Framework :: Django',
        'Framework :: Django :: 4.0',
        'Framework :: Django :: 4.1',
        'Framework :: Django :: 4.2',
        'Framework :: Django :: 5.0',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: 3.11',
        'Programming Language :: Python :: 3.12',
        'Topic :: Internet :: WWW/HTTP',
        'Topic :: Internet :: WWW/HTTP :: Dynamic Content',
    ],
)